"""
Django settings for HomeServiceBackend2 project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^sq(sw%gc=67m9in#b0q2h1-#qy^mfc(a%d(i!e4-bc4^!gr9q"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'home'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "HomeServiceBackend2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "HomeServiceBackend2.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 默认
        'NAME': 'homeservice2',  # 连接的数据库  #一定要存在的数据库名
        'HOST': '127.0.0.1',  # mysql的ip地址
        'PORT': 3306,  # mysql的端口
        'USER': 'root', # mysql的用户名
        'PASSWORD': '1234'  # mysql的密码
        }
}
# DATABASES = {
#    'default': {
#       'ENGINE': 'djongo',
#       'ENFORCE_SCHEMA': True,
#       'NAME': 'homeservice2',
#       'HOST': 'host-name or ip address',
#       'PORT': 27017,
#       'USER': 'db-username',
#       'PASSWORD': 'password',
#       'AUTH_SOURCE': 'db-name',
#       'AUTH_MECHANISM': 'SCRAM-SHA-1',
#       'REPLICASET': 'replicaset',
#       'SSL': 'ssl',
#       'SSL_CERTFILE': 'ssl_certfile',
#       'SSL_CA_CERTS': 'ssl_ca_certs',
#       'READ_PREFERENCE': 'read_preference'
#    }
# }
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# 多语言配置更改语言为中文
LANGUAGE_CODE = "zh-hans"
# 时区
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# simepleui
# 去掉默认Logo或换成自己Logo链接
SIMPLEUI_LOGO = (
    "https://i0.hdslb.com/bfs/face/245cab06813938c7f4a4cb2a8e43ed9f06be539d.jpg"
)
SIMPLEUI_HOME_PAGE = "/home/dashboard/"
SIMPLEUI_HOME_TITLE = "数据大屏"
SIMPLEUI_HOME_ICON = "fa fa-eye"
import time

SIMPLEUI_CONFIG = {
    "system_keep": True,
    'menu_display': ['数据大屏', '服务人员信息管理', "顾客信息发布", '数据统计分析', '纠纷审核与处理', '家政服务预约',
                     '认证和授权'],
    # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    "dynamic": True,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    "menus": [
        {
            "name": "服务人员信息管理",
            "icon": "fa fa-file",  # 二级菜单
            "models": [
                {
                    "name": "服务人员信息建档",
                    "icon": "far fa-surprise",
                    "url": "/home/workercreat/",
                },
                {
                    "name": "服务人员信息更改",
                    "icon": "far fa-surprise",
                    "url": '/admin/home/workerprofile/'
                },
                {
                    "name": "服务人员信息注销",
                    "icon": "far fa-surprise",
                    "url": '/admin/home/workerprofile/'
                    
                },
            ],
        },
        {
            "name": "数据统计分析",
            "icon": "fa fa-file",
            "models": [
                {
                    "name": "服务人员数据统计",
                    "icon": "fab fa-github",
                    "url": "/home/page41/",
                },
                {
                    "name": "顾客数据统计",
                    "icon": "fab fa-github",
                    "url": "/home/page42/",
                },
                {
                    "name": "服务记录数据统计",
                    "url": "/home/page43/",
                    "icon": "fab fa-github",
                },
                {
                    "name": "服务纠纷数据统计",
                    "url": "/home/page44/",
                    "icon": "fab fa-github",
                },
            ],
        },
        {
            "name": "顾客信息发布",
            "icon": "fa fa-file",  # 二级菜单
            "models": [
                {
                    "name": "服务排班发布",
                    "url": "https://www.baidu.com",
                    "icon": "fab fa-github",
                },
            ],
        },
        {
            "name": "纠纷审核与处理",
            "icon": "fa fa-file",  # 二级菜单
            "models": [
                {
                    "name": "纠纷审核",
                    "icon": "far fa-surprise",
                },
                {
                    "name": "纠纷处理",
                    "icon": "far fa-surprise",
                },
            ],
        },
    ],
}
