"""
Django settings for homeServiceBackend project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-lh9fwz*n+!0lemvbg4ua*m@)z3)aojg+7-*^(*yj-=tl(qyqts"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
	"simpleui",
	"django.contrib.admin",
	"django.contrib.auth",
	"django.contrib.contenttypes",
	"django.contrib.sessions",
	"django.contrib.messages",
	"django.contrib.staticfiles",
	"rest_framework",
	"drf_yasg",
	"home",
]

MIDDLEWARE = [
	"django.middleware.security.SecurityMiddleware",
	"django.contrib.sessions.middleware.SessionMiddleware",
	"django.middleware.common.CommonMiddleware",
	"django.middleware.csrf.CsrfViewMiddleware",
	"django.contrib.auth.middleware.AuthenticationMiddleware",
	"django.contrib.messages.middleware.MessageMiddleware",
	"django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "homeServiceBackend.urls"
import os

TEMPLATES = [
	{
		"BACKEND": "django.template.backends.django.DjangoTemplates",  # "DIRS": [],
		"DIRS": [os.path.join(BASE_DIR, "templates")],
		"APP_DIRS": True,
		"OPTIONS": {
			"context_processors": [
				"django.template.context_processors.debug",
				"django.template.context_processors.request",
				"django.contrib.auth.context_processors.auth",
				"django.contrib.messages.context_processors.messages",
			],
		},
	},
]

WSGI_APPLICATION = "homeServiceBackend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
	"default": {
		"ENGINE": "django.db.backends.mysql",
		"NAME": "homeservice",
		"USER": "root",  # 'USER': 'root',
		# 'PASSWORD': 'WangAliyun2024..?..?',
		"PASSWORD": "1234",
		"HOST": "localhost",  # 'HOST': '8.130.67.132',
		"PORT": 3306,
	}
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
	},
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# 多语言配置更改语言为中文
LANGUAGE_CODE = "zh-hans"
# 时区
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
REST_FRAMEWORK = {
	"DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
	"DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
	"PAGE_SIZE": 20,
	"DEFAULT_THROTTLE_CLASSES": [
		"rest_framework.throttling.AnonRateThrottle",
		"rest_framework.throttling.UserRateThrottle",
	],
	"DEFAULT_THROTTLE_RATES": {"anon": "60/min", "user": "600/min"},
}

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings
SWAGGER_SETTINGS = {"LOGIN_URL": "/auth/login/", "LOGOUT_URL": "/auth/logout/"}
# simepleui
# 去掉默认Logo或换成自己Logo链接
SIMPLEUI_LOGO = (
	"https://i0.hdslb.com/bfs/face/245cab06813938c7f4a4cb2a8e43ed9f06be539d.jpg"
)
SIMPLEUI_HOME_PAGE = "/home/dashboard/"
SIMPLEUI_HOME_TITLE = "数据大屏"
SIMPLEUI_HOME_ICON = "fa fa-eye"
import time

SIMPLEUI_CONFIG = {
	"system_keep": True,
	'menu_display': ['数据大屏', '服务人员信息审核', "顾客信息发布", '数据统计分析', '纠纷审核与处理', '家政服务预约',
	                 '认证和授权'],
	# 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
	"dynamic": True,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
	"menus": [
		{
			"name": "服务人员信息审核",
			"icon": "fa fa-file",  # 二级菜单
			"models": [
				{
					"name": "服务人员信息审批",
					"icon": "far fa-surprise",
				},
			],
		},
		{
			"name": "数据统计分析",
			"icon": "fa fa-file",
			"models": [
				{
					"name": "服务人员数据统计",
					"icon": "fab fa-github",
					"url": "/home/page41/",
				},
				{
					"name": "顾客数据统计",
					"icon": "fab fa-github",
					"url": "/home/page42/",
				},
				{
					"name": "服务记录数据统计",
					"url": "https://www.wezoz.com",
					"icon": "fab fa-github",
				},
				{
					"name": "服务纠纷数据统计",
					"url": "https://www.wezoz.com",
					"icon": "fab fa-github",
				},
			],
		},
		{
			"name": "顾客信息发布",
			"icon": "fa fa-file",  # 二级菜单
			"models": [
				{
					"name": "服务排班发布",
					"url": "https://www.baidu.com",
					"icon": "fab fa-github",
				},
			],
		},
		{
			"name": "纠纷审核与处理",
			"icon": "fa fa-file",  # 二级菜单
			"models": [
				{
					"name": "纠纷审核",
					"icon": "far fa-surprise",
				},
				{
					"name": "纠纷处理",
					"icon": "far fa-surprise",
				},
			],
		},
	],
}
