# Generated by Django 4.2 on 2024-05-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_workerprofile_qualification_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
