# Generated by Django 4.2 on 2024-05-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_order_preferred_time_order_preferred_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cost",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="服务持续时长"
            ),
        ),
    ]
