# Generated by Django 4.2 on 2024-05-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_order_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
