# Generated by Django 4.2 on 2024-05-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_order_duration_alter_order_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("待确认", "待确认"),
                    ("已确认", "已确认"),
                    ("服务人员开始服务", "服务人员开始服务"),
                    ("顾客确认开始服务", "顾客确认开始服务"),
                    ("进行中", "进行中"),
                    ("已完成", "已完成"),
                    ("已取消", "已取消"),
                ],
                default="待确认",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
    ]
