# Generated by Django 4.2 on 2024-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("待处理", "待处理"),
                    ("已处理", "已处理"),
                    ("已评分", "已评分"),
                ],
                default="待处理",
                max_length=20,
                verbose_name="纠纷投诉处理状态",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("待确认", "待确认"),
                    ("已确认", "已确认"),
                    ("服务人员开始服务", "服务人员开始服务"),
                    ("顾客确认开始服务", "顾客确认开始服务"),
                    ("进行中", "进行中"),
                    ("已完成", "已完成"),
                    ("已评价", "已评价"),
                    ("已取消", "已取消"),
                ],
                default="待确认",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
    ]
